### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Juan-de-Costa-Rica** [lflare/lemmy-subscriber-bot#3]
```bash
2023-07-05 18:25:09.244 | ERROR    | __main__:subscribe_community:182 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           │           │     │    │       └ {}
           │           │     │    └ <property object at 0x7f6824271bc0>
           │           │     └ <Response [408]>
           │           └ <function loads at 0x7f68250ca0c0>
           └ <module 'json' from '/usr/local/lib/python3.11/json/__init__.py'>
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x7f68250c9a80>
           └ <json.decoder.JSONDecoder object at 0x7f68250cc290>
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x7f68253b4ee0>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x7f68250c9b20>
               └ <json.decoder.JSONDecoder object at 0x7f68250cc290>
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f68250fea20>
    └ <Thread(Thread-2 (community_subscriber_thread), started daemon 140085250935608)>
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f68250fe700>
    └ <Thread(Thread-2 (community_subscriber_thread), started daemon 140085250935608)>
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2 (community_subscriber_thread), started daemon 140085250935608)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-2 (community_subscriber_thread), started daemon 140085250935608)>
    │    └ <bound method Bot.community_subscriber_thread of <__main__.Bot object at 0x7f6823d2c110>>
    └ <Thread(Thread-2 (community_subscriber_thread), started daemon 140085250935608)>

  File "///bot.py", line 205, in community_subscriber_thread
    self.subscribe_community(community_addr)
    │    │                   └ 'https://lemmy.world/c/wefwef'
    │    └ <function Bot.subscribe_community at 0x7f6823d137e0>
    └ <__main__.Bot object at 0x7f6823d2c110>

> File "///bot.py", line 165, in subscribe_community
    id, resolved = self.resolve_community(community_addr)
                   │    │                 └ 'https://lemmy.world/c/wefwef'
                   │    └ <function Bot.resolve_community at 0x7f6823d13740>
                   └ <__main__.Bot object at 0x7f6823d2c110>

  File "///bot.py", line 148, in resolve_community
    if "error" in r.json():
                  │ └ <function Response.json at 0x7f6823ff4fe0>
                  └ <Response [408]>

  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
          └ <class 'requests.exceptions.JSONDecodeError'>

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```bash
2023-07-05 18:25:09.690 | INFO     | __main__:get_instance_communities:125 - QUEUED RESOLVE: lemmy.studio/atheistmemes
2023-07-05 18:25:10.106 | INFO     | __main__:get_instance_communities:122 - QUEUED SUBSCRIBE: lemmy.click/artificial_intel
```
```bash
Exception in thread Thread-1 (community_resolver_thread):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "//bot.py", line 194, in community_resolver_thread
    self.resolve_community(community_addr)
  File "//bot.py", line 148, in resolve_community
    if "error" in r.json():
                  ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lflare** [comment]
This is likely just transient error from the bot being unable to reach some of the instances. It's overly verbose, but I think the error can be ignored. I'll see how better to handle this.

**Comment by lflare** [comment]
@Juan-de-Costa-Rica I've made a fair bit of changes since this issue, could you try it and re-create the issue if it's occurring again?
